DELETE FROM JHI_USER_AUTHORITY;

DELETE FROM JHI_AUTHORITY;

DELETE FROM JHI_USER;

INSERT INTO JHI_AUTHORITY VALUES('ROLE_ADMIN');
INSERT INTO JHI_AUTHORITY VALUES('ROLE_USER');


INSERT INTO JHI_USER ("ID","LOGIN","PASSWORD_HASH","FIRST_NAME","LAST_NAME","EMAIL","ACTIVATED","LANG_KEY","CREATED_BY","CREATED_DATE") VALUES(1,'system','$2a$10$mE.qmcV0mFU5NcKh73TZx.z4ueI/.bDWbj0T1BYyqP481kGGarKLG','System','System','system@localhost',true,'en','System', now());

INSERT INTO JHI_USER ("ID","LOGIN","PASSWORD_HASH","FIRST_NAME","LAST_NAME","EMAIL","ACTIVATED","LANG_KEY","CREATED_BY","CREATED_DATE") VALUES(2,'admin','$2a$10$ela.3ysirQaVXS5i1hwYDuJzGMMMmv3G1zcROxTRci9/pXyw/C2ve','Administrator','Administrator','admin@localhost',true,'en','system',now());
INSERT INTO JHI_USER ("ID","LOGIN","PASSWORD_HASH","FIRST_NAME","LAST_NAME","EMAIL","ACTIVATED","LANG_KEY","CREATED_BY","CREATED_DATE") VALUES(3,'user','$2a$10$VEjxo0jq2YG9Rbk2HmX9S.k1uZBGYUHdUcid3g/vfiEl7lwWgOH/K','User','User','user@localhost',true,'en','system',now());




INSERT INTO JHI_USER_AUTHORITY ("USER_ID","AUTHORITY_NAME") VALUES(1,'ROLE_ADMIN');

INSERT INTO JHI_USER_AUTHORITY ("USER_ID","AUTHORITY_NAME") VALUES(1,'ROLE_USER');

INSERT INTO JHI_USER_AUTHORITY ("USER_ID","AUTHORITY_NAME") VALUES(2,'ROLE_USER');

INSERT INTO JHI_USER_AUTHORITY ("USER_ID","AUTHORITY_NAME") VALUES(2,'ROLE_ADMIN');

INSERT INTO JHI_USER_AUTHORITY ("USER_ID","AUTHORITY_NAME") VALUES(3,'ROLE_USER');

